### ISSUE TITLE
Grpc Message Size Constraints

### ISSUE THREAD

**Issue by mabmayer** [codenotary/immudb#1183]
**What would you like to be added or enhanced**
Get rid of grpc message size constraints.

**Why is this needed**
When working with large datasets, it is very cumbersome to split requests in parts, just to assemble it later on in the application.

**Additional context**
ERROR: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (13228895 vs. 4194304)

Streaming API should be the solution.

**Comment by vitoalmeida** [comment]
I'm facing the same error! Is there any way to fix this?

**Comment by ostafen** [comment]
@vitoalmeida, in which endpoint are you experimenting the issue?

**Comment by vitoalmeida** [comment]
@ostafen `/sqlquery`

**Comment by ostafen** [comment]
Which version of immudb and client SDK are you using?

**Comment by vitoalmeida** [comment]
I'm using docker images, `codenotary/immugw:latest` and `codenotary/immudb:latest`. I make my requests using immugw endpoints.

My docker compose file:
```
version: '3.8'
name: immudb
services:
  immudb:
    image: codenotary/immudb:latest
    container_name: immudb
    volumes:
      - ./configs/immudb.toml:/configs/immudb.toml
      - immudb-data:/var/lib/immudb
    command: ['--config', '/configs/immudb.toml']
    restart: unless-stopped
    networks:
      - immudb-network
    ports:
      - '8081:8080'
      - '3322:3322'

  immugw:
    image: codenotary/immugw:latest
    container_name: immugw
    ports:
      - '3323:3323'
    environment:
      - IMMUGW_IMMUDB_ADDRESS=immudb
      - IMMUGW_IMMUDB_PORT=3322
    restart: unless-stopped
    depends_on:
      - immudb
    networks:
      - immudb-network

networks:
  immudb-network:

volumes:
  immudb-data:
```

An example of my Rust API request:
```
let url = format!("{}/db/sqlquery", &DATABASE_URL.to_string());

    let client = reqwest::Client::new();

    let mut headers = HeaderMap::new();
    headers.insert(CONTENT_TYPE, HeaderValue::from_static("application/json"));
    headers.insert(
        AUTHORIZATION,
        HeaderValue::from_str(get_immudb_token()?.as_str())
            .map_err(|err| BaseError::InternalServerError(err.to_string()))?,
    );

    let body = serde_json::json!({
        "sql": sql_command
    });

    let mut attempt = 0;
    let max_attempts = 3;

    loop {
        let response = client
            .post(&url)
            .headers(headers.clone())
            .json(&body)
            .send()
            .await;
```
